### ISSUE TITLE
Падение, при нажатии назад из CreateMapFragment

### ISSUE THREAD

**Issue by Trunker2010** [rjhdby/android_motoDTP_v2#117]
При каких то условиях приложение, падает при нажатии назад из CreateMapFragment.
Лог:
```
2021-09-21 16:24:18.708 6951-6951/motocitizen.main E/AndroidRuntime: FATAL EXCEPTION: main
    Process: motocitizen.main, PID: 6951
    java.lang.ClassCastException: motocitizen.domain.lcenstate.LcenState$Loading cannot be cast to motocitizen.domain.lcenstate.LcenState$Content
        at motocitizen.domain.lcenstate.LcenState.asContent(LcenState.kt:18)
        at motocitizen.presentation.screens.home.HomeViewModel$loadAccidentList$1.invoke(HomeViewModel.kt:51)
        at motocitizen.presentation.screens.home.HomeViewModel$loadAccidentList$1.invoke(HomeViewModel.kt:16)
        at motocitizen.presentation.base.viewmodel.BaseViewModel.safeSubscribe(BaseViewModel.kt:29)
        at motocitizen.presentation.screens.home.HomeViewModel.loadAccidentList(HomeViewModel.kt:45)
        at motocitizen.presentation.screens.home.HomeFragment$loadAccidentList$1.invoke(HomeFragment.kt:77)
        at motocitizen.presentation.screens.home.HomeFragment$loadAccidentList$1.invoke(HomeFragment.kt:21)
        at motocitizen.presentation.screens.root.RootActivity$updateLastLocation$1$1.onSuccess(RootActivity.kt:102)
        at motocitizen.presentation.screens.root.RootActivity$updateLastLocation$1$1.onSuccess(RootActivity.kt:44)
        at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by elagin** [comment]
Один в один https://github.com/rjhdby/android_motoDTP_v2/issues/115
