### ISSUE TITLE
Падение на старте если не включена геолокация

### ISSUE THREAD

**Issue by elagin** [rjhdby/android_motoDTP_v2#18]
Нужно добавить уведомление юзера о том, что необходимо включить геолокацию.
Если геолокация не была включена, показывать центр Москвы.
Выключаем геолокацию на девайсе, запускаем приложение, оно падает, а в логе:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: motocitizen.main, PID: 31407
    java.lang.NullPointerException
        at motocitizen.presentation.screens.root.RootViewModel.starLocationUpdate(RootViewModel.kt:36)
        at motocitizen.presentation.screens.root.RootActivity.startLocationUpdate(RootActivity.kt:89)
        at motocitizen.presentation.screens.root.RootActivity.checkLocationPermission(RootActivity.kt:55)
        at motocitizen.presentation.screens.root.RootActivity.onStart(RootActivity.kt:172)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7986)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by Trunker2010** [comment]
![Screenshot_20210512_213047_motocitizen.main.jpg](https://user-images.githubusercontent.com/47688469/118026472-7f15b880-b369-11eb-853c-8cfe9605a233.jpg)
